# Deployment do MongoDB
apiVersion: apps/v1
kind: Deployment
metadata:
	name: mongodb
spec:
	replicas: 1
	selector:
		matchlabels:
			app: mongodb
	template:
		metadata:
			labels:
				app: mongodb
		spec:
			containers:
				- name: mongodb
				image: mongo:4.4.6
				ports:
					- containerPort:27017
				env:
					- name: MONGO_INITDB_ROOT_USERNAME
					   value: mongouser
					- name: MONGO_INITDB_ROOT_PASSWORD
					   value: mongopwd
---
# Service do MongoDB
apiVersion: v1
kind: Service
metadata:
	name: mongodb
spec:
	selector:
		app: mongodb
	ports:
		- port: 27017
	type: ClusterIP
---
# Deployment da aplicacao web
apiVersion: apps/v1
kind: Deployment
metadata:
	name: web
spec:
	replicas: 1
	selector:
		matchlabels:
			app: web
	template:
		metadata:
			labels:
				app: web
		spec:
			containers:
				- name: web
				image: vtgdias/rotten-potatoes:v1
				ports:
					- containerPort:5000
				env:
					- name: MONGODB_DB
					   value: "admin"
					- name: MONGODB_HOST
					   value: "mongodb"
					- name: MONGODB_PORT
					   value: "27017"
					- name: MONGODB_USERNAME
					   value: "mongouser"
					- name: MONGODB_PASSWORD
					   value: "mongopwd"
---
# Service da aplicacao web
apiVersion: v1
kind: Service
metadata:
	name: web
spec:
	selector:
		app: web
	ports:
		- port: 80
		targetPort: 5000
		nodePort: 30000
	type: NodePort
