name: CI/CD


on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            vtgdias/rotten-potatoes:latest
            vtgdias/rotten-potatoes:${{ github.run_number }}
            
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    
    steps:
      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1.1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v1.3
        with:
          images: |
            vtgdias/rotten-potatoes:${{ github.run_number }}
          manifests: |
            ../k8s/deployment.yaml
    
